In [17]:
import numpy as np
import matplotlib.pyplot as plt


#For A1, Newton-Raphson Method to find zero near -0.5 with initial guess of x=-1.6
x = np.array([-1.6])

for j in range(1000):
  x = np.append(
      x, x[j]-(x[j] * np.sin(3*x[j])-np.exp(x[j]))
      / (-np.exp(x[j]) + np.sin(3*x[j]) + 3*x[j]*np.cos(3*x[j])))

  if abs(x[j]-x[j+1]) < 1e-6:
    break

A1 = x[0:j + 2]
print("A1 = \n",A1)


#For A2, bisection method to find the zero between x=-0.7 and x=-0.4
xr = -.4; xl = -.7; xmid = np.array([])
for i in range(0, 100):
  xc = (xr + xl)/2
  fc = xc * np.sin(3*xc)-np.exp(xc)
  xmid = np.append(xmid, xc)

  if ( fc > 0 ):
    xl = xc

  else:
    xr = xc

  if (abs(fc) < 1e-6 ):
    break

A2 = xmid
print("\n\nA2 = \n",A2)


#For A3, we need to show a 1 row by 2 column matrix with the number of iterations from the above methods, respectively
A3 = np.array([j+1,i+1])
print("\n\nA3 =",A3)


#Setting up A, B, C, D, x, y, and z for A4-A12
A = np.array([[1,2],
             [-1,1]])
B = np.array([[2,0],
              [0,2]])
C = np.array([[2,0,-3],
              [0,0,-1]])
D = np.array([[1,2],
              [2,3],
              [-1,0]])
x = np.array([[1],
              [0]])
y = np.array([[0],
              [1]])
z = np.array([[1],
              [2],
              [-1]])

A4 = A+B
print("\n\nA4 =\n", A4)

A5_tmp = 3*x - 4*y
A5 = np.array(A5_tmp[0])
A5 = np.append(A5, A5_tmp[1])
print("\n\nA5 =\n", A5)

A6_tmp = A@x
A6 = np.array(A6_tmp[0])
A6 = np.append(A6, A6_tmp[1])
print("\n\nA6 =\n", A6)

A7_tmp = B@(x-y)
A7 = np.array(A7_tmp[0])
A7 = np.append(A7, A7_tmp[1])
print("\n\nA7 =\n", A7)

A8_tmp = D@x
A8 = np.array(A8_tmp[0])
A8 = np.append(A8, A8_tmp[1])
A8 = np.append(A8, A8_tmp[2])
print("\n\nA8 =\n", A8)

A9_tmp = (D@y)+z
A9 = np.array(A9_tmp[0])
A9 = np.append(A9, A9_tmp[1])
A9 = np.append(A9, A9_tmp[2])
print("\n\nA9 =\n", A9)

A10 = A@B
print("\n\nA10 =\n", A10)

A11 = B@C
print("\n\nA11 =\n", A11)

A12 = C@D
print("\n\nA12 =\n", A12)


A1 = 
 [-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]


A2 = 
 [-0.55       -0.625      -0.5875     -0.56875    -0.578125   -0.5734375
 -0.57109375 -0.56992188 -0.57050781 -0.57080078 -0.5706543  -0.57072754
 -0.57076416 -0.57078247 -0.57079163 -0.57078705 -0.57078934]


A3 = [11 17]


A4 =
 [[ 3  2]
 [-1  3]]


A5 =
 [ 3 -4]


A6 =
 [ 1 -1]


A7 =
 [ 2 -2]


A8 =
 [ 1  2 -1]


A9 =
 [ 3  5 -1]


A10 =
 [[ 2  4]
 [-2  2]]


A11 =
 [[ 4  0 -6]
 [ 0  0 -2]]


A12 =
 [[5 4]
 [1 0]]
